//generated by: NURIBEIR
//generated data: 02/04/2019
define({
	//in case there is no label
	'no-label':'Error: no label available'
	//Domain: Party Management
	//SourceFile: partymanagement.xlsx
	//Party Management domai
});